Add files via upload

diff --git a/.github/workflows/all.yml b/.github/workflows/all.yml
--- a/.github/workflows/all.yml
+++ b/.github/workflows/all.yml
@@ -19,7 +19,7 @@ jobs:
       contents: write
 
     steps:
-      - name: Checkout repository
+      - name: Checkout
         uses: actions/checkout@v4
         with:
           fetch-depth: 1
@@ -30,43 +30,41 @@ jobs:
         with:
           python-version: "3.11"
 
-      - name: Install dependencies
+      - name: Install Dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install requests
-          pip install aiohttp
+          pip install requests aiohttp
 
-      - name: Restore Python script from secret
+      - name: Decode Python Script
         run: |
           echo "${{ secrets.ALL_PY }}" | base64 -d > all.py
           chmod +x all.py
 
-      - name: Run scraper
+      - name: Run Scr
         run: |
           python all.py
 
-      - name: Commit playlist
+      - name: Commit Playlist
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          FILE="a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/all.php"
+          git config --global user.name "yanshdroid[bot]"
+          git config --global user.email "yanshdroid[bot]@users.noreply.github.com"
 
-          git config --global user.name "github-actions"
-          git config --global user.email "github-actions@github.com"
+          FILE="a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/all.php"
 
           if [ -f "$FILE" ]; then
             git add "$FILE"
-            git commit -m "Update ALLPHP playlist $(date)" || echo "No changes"
+            git commit -m "Auto update playlist $(date)" || echo "No changes"
 
-            # retry push untuk multi runner (10 runner)
+            # retry push jika banyak runner
             for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
             do
               git pull --rebase --autostash origin main
               git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main && break
-              echo "Push failed, retry $i..."
+              echo "Push failed. retry $i..."
               sleep 5
             done
-
           else
-            echo "all.m3u not found"
+            echo "all.php not found"
           fi
diff --git a/.github/workflows/lve0.yml b/.github/workflows/lve0.yml
--- a/.github/workflows/lve0.yml
+++ b/.github/workflows/lve0.yml
@@ -14,12 +14,11 @@ on:
 jobs:
   merge-and-commit:
     runs-on: ubuntu-22.04
-
     permissions:
       contents: write
 
     steps:
-      - name: Checkout repository
+      - name: Checkout
         uses: actions/checkout@v4
         with:
           fetch-depth: 1
@@ -28,44 +27,48 @@ jobs:
       - name: Setup Python
         uses: actions/setup-python@v5
         with:
-          python-version: "3.11"
+          python-version: "3.10"
 
-      - name: Install dependencies
+      - name: Install Dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install aiohttp
+          pip install aiohttp unidecode
 
-      - name: Restore Python script from secret
+      - name: Decode Script
         run: |
           echo "${{ secrets.EPEP_PY }}" | base64 -d > epep.py
           chmod +x epep.py
 
-      - name: Run scraper
+      - name: Create Folder Path
         run: |
-          python epep.py
+          mkdir -p a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z
 
-      - name: Commit playlist
+      - name: Run Script
+        run: |
+          python3 epep.py
+
+      - name: Commit Result
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          FILE="a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/lve0.m3u"
+          FILE="a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/live0.m3u"
 
-          git config --global user.name "github-actions"
-          git config --global user.email "github-actions@github.com"
+          git config --global user.name "yanshdroid[bot]"
+          git config --global user.email "yanshdroid[bot]@users.noreply.github.com"
 
           if [ -f "$FILE" ]; then
-            git add "$FILE"
-            git commit -m "Update LVE0M3U playlist $(date)" || echo "No changes"
 
-            # retry push untuk multi runner (10 runner)
-            for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
-            do
-              git pull --rebase --autostash origin main
-              git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main && break
-              echo "Push failed, retry $i..."
-              sleep 5
-            done
+            git add "$FILE"
+
+            if ! git diff --cached --quiet; then
+              git commit -m "🔄 Auto update $(date +'%Y-%m-%d %H:%M:%S')"
+            else
+              echo "No changes to commit"
+            fi
+
+            git pull --rebase --autostash origin main
+            git push origin main
 
           else
-            echo "lve0.m3u not found"
+            echo "live0.m3u not found"
           fi
