Add files via upload

diff --git a/.github/workflows/hh.yml b/.github/workflows/hh.yml
--- a/.github/workflows/hh.yml
+++ b/.github/workflows/hh.yml
@@ -1,4 +1,4 @@
-name: Live ajga
+name: LIVE Ajgha
 
 on:
   schedule:
@@ -14,29 +14,35 @@ on:
 jobs:
   merge-and-commit:
     runs-on: ubuntu-22.04
+
     permissions:
       contents: write
 
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v3
         with:
+          fetch-depth: 0
           token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Setup Python
-        uses: actions/setup-python@v5
+        uses: actions/setup-python@v4
         with:
           python-version: "3.11"
 
-      - name: Install dependencies
-        run: pip install requests
+      - name: Install Dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install requests
 
-      - name: Create Python Script From Base64 Secret
+      - name: Decode Python Script
         run: |
           echo "${{ secrets.HH_PY }}" | base64 -d > hh.py
+          chmod +x hh.py
 
-      - name: Run Script
-        run: python hh.py
+      - name: Run Scr
+        run: |
+          python hh.py
 
       - name: Commit Playlist
         env:
@@ -45,8 +51,20 @@ jobs:
           git config --global user.name "yanshdroid[bot]"
           git config --global user.email "yanshdroid[bot]@users.noreply.github.com"
 
-          git add a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/live.php
+          FILE="a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/live.php"
 
-          git commit -m "Auto Update $(date)" || echo "No changes"
+          if [ -f "$FILE" ]; then
+            git add "$FILE"
+            git commit -m "Auto update playlist $(date)" || echo "No changes"
 
-          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
+            # retry push jika banyak runner
+            for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
+            do
+              git pull --rebase --autostash origin main
+              git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main && break
+              echo "Push failed. retry $i..."
+              sleep 5
+            done
+          else
+            echo "hh.php not found"
+          fi
