Update lve0.yml

diff --git a/.github/workflows/lve0.yml b/.github/workflows/lve0.yml
--- a/.github/workflows/lve0.yml
+++ b/.github/workflows/lve0.yml
@@ -57,10 +57,18 @@ jobs:
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
 
           if [ -f "$FILE" ]; then
+
             git add "$FILE"
-            git diff --quiet && git diff --staged --quiet || git commit -m "🔄 Auto update $(date +'%Y-%m-%d %H:%M:%S')"
-            git pull --rebase https://x-access-token:${GITHUB_TOKEN}@github.com/eyayq/eliv.git main
-            git push https://x-access-token:${GITHUB_TOKEN}@github.com/eyayq/eliv.git
+
+            if ! git diff --cached --quiet; then
+              git commit -m "🔄 Auto update $(date +'%Y-%m-%d %H:%M:%S')"
+            else
+              echo "No changes to commit"
+            fi
+
+            git pull --rebase --autostash origin main
+            git push origin main
+
           else
-            echo "live.m3u not found"
+            echo "live0.m3u not found"
           fi
