Update lve1.yml

diff --git a/.github/workflows/lve1.yml b/.github/workflows/lve1.yml
--- a/.github/workflows/lve1.yml
+++ b/.github/workflows/lve1.yml
@@ -14,11 +14,11 @@ on:
 jobs:
   merge-and-commit:
     runs-on: ubuntu-22.04
+
     permissions:
       contents: write
 
     steps:
-
       - name: Checkout
         uses: actions/checkout@v4
         with:
@@ -59,8 +59,16 @@ jobs:
 
           if [ -f "$FILE" ]; then
             git add "$FILE"
-            git diff --quiet && git diff --staged --quiet || git commit -m "🔄 Auto update $(date +'%Y-%m-%d %H:%M:%S')"
-            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
+            git commit -m "🔄 Auto update $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes"
+
+            # retry push jika ada runner lain yang push duluan
+            for i in 1 2 3 4 5
+            do
+              git pull --rebase origin main
+              git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git && break
+              echo "Push failed. retry $i..."
+              sleep 3
+            done
           else
-            echo "live.m3u not found"
+            echo "live1.m3u not found"
           fi
